#!/usr/bin/env node
/**
 * Trusted-side helpers for the autofix workflow (docs/automated-fix.md §3–§5).
 * Three subcommands, none of which touch a model or a secret:
 *
 *   prompt  --source <id> --evidence <path> --error <text> --workflow <name> [--fixture-name <name>]
 *           Render .github/autofix/prompt.md for the generate job.
 *
 *   check   --patch <file> --source <id>
 *           Apply the allowlist and constraint checks to a generated patch.
 *           Exit 0 when clean, 1 with the violations listed otherwise.
 *
 *   pr-body --source <id> --error <text> --evidence-url <url> --values-file <path> --patch <file>
 *           Render the pull request body: error, evidence link, values table, checklist.
 *
 *   fixture --source <id> --evidence <path> --url <sourceUrl> --date <YYYY-MM-DD> --out <path>
 *           Reduce the captured page to the block the parser reads and write it as the
 *           fixture, before the model runs. Exit 1 if it cannot be brought under 32 KB.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import { checkPatch, parsePatch, sanitiseEvidence, sanitiseTextEvidence } from '../lib/autofix-propose.js';
import { AUTOFIX_SOURCES } from '../lib/autofix-sources.js';

function arg(name, fallback = null) {
  const index = process.argv.indexOf(name);
  return index === -1 ? fallback : process.argv[index + 1];
}

function source(sourceId) {
  const entry = AUTOFIX_SOURCES[sourceId];
  if (!entry) throw new Error(`unknown source ${sourceId}`);
  return entry;
}

export function renderPrompt(template, values) {
  return template.replace(/\$\{([A-Z_]+)\}/g, (match, key) => (key in values ? String(values[key]) : match));
}

export function renderPrBody({ sourceId, entry, error, evidenceUrl, valuesTable, files, fixtures }) {
  return [
    `## Autofix: \`${sourceId}\` (${entry.category})`,
    '',
    'This pull request was generated from the failing page captured by the scrape run. It was',
    'checked by the allowlist and the test suite, but **it has not been read by a person**.',
    'Review the values below against the official page, then read the diff.',
    '',
    '### Failure',
    '',
    '```',
    String(error || 'unknown').slice(0, 1000),
    '```',
    '',
    `Evidence: ${evidenceUrl || '(artifact on the triggering run)'}`,
    '',
    '### What the patched parser produces for the new fixture',
    '',
    valuesTable || '_no values table_',
    '',
    '### Files',
    '',
    ...files.map(file => `- \`${file}\`${fixtures.includes(file) ? ' (new fixture)' : ''}`),
    '',
    '### Review checklist',
    '',
    '- [ ] The values table matches the official page for every weekday and interval',
    '- [ ] No new imports; nothing touching `fetch`, `child_process`, `eval`, `process.env`',
    '- [ ] Changes are confined to parsing; no behaviour outside this source',
    '- [ ] The fixture header names the URL and capture date, and the fixture is a sanitised reduction',
    '- [ ] After merge: re-run the scrape (`/rerun <category>` in Telegram)',
    '',
    '_Generated by `autofix-parser.yml`; see `docs/automated-fix.md`._',
  ].join('\n');
}

async function main() {
  const command = process.argv[2];
  if (command === 'prompt') {
    const sourceId = arg('--source');
    const entry = source(sourceId);
    const template = await readFile(arg('--template', '.github/autofix/prompt.md'), 'utf8');
    const today = new Date().toISOString().slice(0, 10);
    process.stdout.write(renderPrompt(template, {
      SOURCE_ID: sourceId,
      WORKFLOW: arg('--workflow', `update-${entry.category}-hours`),
      ERROR: arg('--error', 'unknown'),
      EVIDENCE_PATH: arg('--evidence'),
      PARSER_FILE: entry.parserFile,
      TEST_FILE: entry.testFile,
      FIXTURE_NAME: arg('--fixture-name', `${entry.fixture}-${today}.${entry.extension || 'html'}`),
      CATEGORY: entry.category,
    }));
    return;
  }
  if (command === 'check') {
    const sourceId = arg('--source');
    const entry = source(sourceId);
    const patch = await readFile(arg('--patch'), 'utf8');
    const result = checkPatch(patch, { category: entry.category, parserFile: entry.parserFile, testFile: entry.testFile });
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
    if (!result.ok) {
      for (const violation of result.violations) process.stderr.write(`✗ ${violation}\n`);
      process.exitCode = 1;
    }
    return;
  }
  if (command === 'fixture') {
    const sourceId = arg('--source');
    const entry = source(sourceId);
    const evidencePath = arg('--evidence');
    const out = arg('--out');
    if (!evidencePath || !out) throw new Error('fixture needs --evidence and --out');
    const extension = (arg('--extension') || entry.extension || path.extname(evidencePath).slice(1) || 'html').toLowerCase();
    const body = await readFile(evidencePath, 'utf8');
    const options = { sourceUrl: arg('--url'), capturedAt: arg('--date', new Date().toISOString().slice(0, 10)) };
    const result = extension === 'html' ? sanitiseEvidence({ html: body, ...options }) : sanitiseTextEvidence({ body, extension, ...options });
    await mkdir(path.dirname(out), { recursive: true });
    await writeFile(out, result.html);
    process.stdout.write(`${JSON.stringify({ out, bytes: result.bytes, ok: result.ok, root: result.root, originalBytes: Buffer.byteLength(body, 'utf8') })}\n`);
    if (!result.ok) {
      process.stderr.write(`fixture is ${result.bytes} bytes after reduction; over the 32 KB limit\n`);
      process.exitCode = 1;
    }
    return;
  }
  if (command === 'pr-body') {
    const sourceId = arg('--source');
    const entry = source(sourceId);
    const patch = await readFile(arg('--patch'), 'utf8');
    const files = parsePatch(patch).map(file => file.path);
    const fixtures = files.filter(file => file.startsWith('tests/fixtures/'));
    const valuesTable = arg('--values-file') ? await readFile(arg('--values-file'), 'utf8') : null;
    process.stdout.write(renderPrBody({
      sourceId, entry, error: arg('--error'), evidenceUrl: arg('--evidence-url'), valuesTable, files, fixtures,
    }));
    return;
  }
  throw new Error('usage: autofix-propose.mjs <prompt|check|pr-body|fixture> …');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch(error => {
    process.stderr.write(`autofix propose: ${error?.message || error}\n`);
    process.exitCode = 1;
  });
}
