#!/usr/bin/env node
/**
 * generate-seo.mjs — builds the crawlable surface of lionhour.com.
 *
 * Reads the VENUES catalog straight out of index.html (single source of
 * truth, so this can never drift from the app) and writes:
 *
 *   robots.txt              — crawl policy + sitemap pointer
 *   sitemap.xml             — every indexable URL
 *   hours/<slug>.html       — one static, indexable page per venue
 *   hours/index.html        — hub page linking every venue page
 *
 * The static pages carry the *typical semester* hours from the catalog and
 * link to the live tracker. They are regenerated by running:
 *
 *   npm run seo
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadVenues, hasWeeklyHours } from './lib/venues.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://lionhour.com';

/* Crisis / clinical services. The pages exist so the site is complete, but they
   are kept out of search: a student looking for these should land on Columbia's
   own page, not a student project. */
const NOINDEX = new Set(['svr', 'caps', 'medical', 'alice-health']);

/* ── 1. The VENUES catalog, read from index.html ─────────────────── */
const VENUES = loadVenues(ROOT);

/* ── 2. Helpers ───────────────────────────────────────────────────── */
const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const SCHEMA_DAY = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

const CATEGORY = {
  library: {
    label: 'Library', plural: 'Libraries', slug: 'libraries',
    h1: 'Columbia University library hours',
    title: 'Columbia Library Hours — Butler, NoCo, Avery & More | LionHour',
    description: 'Opening hours for every Columbia University library: Butler (open 24 hours during the semester), NoCo, Uris, Avery, Math, SIPA and Milstein. Updated live.',
    intro: 'Butler runs around the clock from Sunday morning through Friday night during the semester; the departmental libraries keep shorter hours and most close early on Saturdays. Hours shift during reading week, finals and breaks.',
  },
  dining: {
    label: 'Dining hall', plural: 'Dining halls', slug: 'dining',
    h1: 'Columbia dining hall hours',
    title: 'Columbia Dining Hall Hours — John Jay, Ferris, JJ\'s Place | LionHour',
    description: 'Today\'s hours for Columbia dining halls: John Jay, Ferris, JJ\'s Place (open overnight), Chef Mike\'s, Chef Don\'s, Faculty House, Grace Dodge and Barnard\'s Hewitt. Updated live.',
    intro: 'Ferris is the all-week anchor, John Jay closes Friday and Saturday this semester, and JJ\'s Place is the overnight option — open from noon until 10 the next morning. Barnard halls load their schedule live.',
  },
  cafe: {
    label: 'Cafe', plural: 'Cafes', slug: 'cafes',
    h1: 'Columbia campus cafe hours',
    title: 'Columbia Cafe Hours — Butler Cafe, Joe Coffee, Cafe East | LionHour',
    description: 'Opening hours for cafes on Columbia\'s campus: Butler Cafe, the three Joe Coffee locations, Cafe East, Uris, Mudd, Everett, Lenfest and Liz\'s Place at Barnard.',
    intro: 'Butler Cafe stays open until midnight Monday to Thursday. The Joe Coffee locations require a Columbia ID for entry, and the Law School cafes close early on Fridays.',
  },
  fitness: {
    label: 'Fitness', plural: 'Gyms & fitness', slug: 'fitness',
    h1: 'Columbia gym hours',
    title: 'Columbia Gym Hours — Dodge Fitness Center & Uris Pool | LionHour',
    description: 'Dodge Fitness Center opening hours, Uris Pool lap-swim times, and Barnard\'s LeFrak gym. See if the gym is open right now at Columbia.',
    intro: 'Dodge opens at 6 AM on weekdays and 8 AM on weekends. The pool keeps its own narrower schedule inside those hours, so check it separately before heading down.',
  },
  student: {
    label: 'Student services', plural: 'Student life & services', slug: 'student-life',
    h1: 'Columbia student services hours',
    title: 'Columbia Student Services Hours — Lerner, Bookstore, Mail Center | LionHour',
    description: 'Office hours for Columbia student services: Lerner Hall, the bookstore, the student mail center, Disability Services, the health insurance office and more.',
    intro: 'Most offices keep weekday business hours; Lerner Hall itself is open later and on weekends. Several services see students by appointment only.',
  },
};

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
  .replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const slugify = name => name.toLowerCase()
  .replace(/['’]/g, '').replace(/&/g, 'and')
  .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/** "09:30" → "9:30 AM"; "24:00" → "midnight" */
function pretty(t) {
  const [hRaw, m] = t.split(':').map(Number);
  if (hRaw === 24 || (hRaw === 0 && m === 0)) return 'midnight';
  if (hRaw === 12 && m === 0) return 'noon';
  const h = hRaw % 12 === 0 ? 12 : hRaw % 12;
  const suffix = hRaw < 12 ? 'AM' : 'PM';
  return m === 0 ? `${h} ${suffix}` : `${h}:${String(m).padStart(2, '0')} ${suffix}`;
}

function dayText(ranges) {
  if (!ranges || !ranges.length) return 'Closed';
  if (ranges.length === 1 && ranges[0][0] === '00:00' && ranges[0][1] === '24:00') return 'Open 24 hours';
  return ranges.map(([o, c]) => `${pretty(o)} – ${pretty(c)}`).join(', ');
}

/** schema.org wants 24h HH:MM; 24:00 is not valid, use 23:59. */
const schemaTime = t => (t === '24:00' ? '23:59' : t);

function openingHoursSpec(hours) {
  const spec = [];
  for (let d = 0; d < 7; d++) {
    const ranges = hours?.[d];
    if (!ranges || !ranges.length) continue;
    for (const [o, c] of ranges) {
      spec.push({
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: `https://schema.org/${SCHEMA_DAY[d]}`,
        opens: schemaTime(o),
        closes: schemaTime(c),
      });
    }
  }
  return spec;
}

const hasHours = hasWeeklyHours;

/** Collapse a week into "Mon–Thu 9 AM – 11 PM · Fri 9 AM – 8 PM · Sat–Sun Closed". */
const DAY_ABBR = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
function weekSummary(hours) {
  const order = [1, 2, 3, 4, 5, 6, 0]; // Monday-first
  const groups = [];
  for (const d of order) {
    const text = dayText(hours?.[d]);
    const last = groups[groups.length - 1];
    if (last && last.text === text) last.days.push(d);
    else groups.push({ text, days: [d] });
  }
  return groups.map(g => {
    const span = g.days.length === 1
      ? DAY_ABBR[g.days[0]]
      : `${DAY_ABBR[g.days[0]]}–${DAY_ABBR[g.days[g.days.length - 1]]}`;
    return `${span} ${g.text}`;
  }).join(' · ');
}

/* ── 3. Build the venue list ──────────────────────────────────────── */
const pages = VENUES.map(v => ({
  ...v,
  slug: slugify(v.name),
  url: `${ORIGIN}/hours/${slugify(v.name)}`,
  catLabel: CATEGORY[v.cat]?.label ?? 'Building',
}));

const byCat = {};
for (const p of pages) (byCat[p.cat] ||= []).push(p);

/* ── 4. Shared chrome ─────────────────────────────────────────────── */
const STYLE = `
:root{--blue:#1D4F91;--light:#75AADB;--bg:#F0F4F8;--surface:#fff;--text:#1a1a2e;
--text2:#5a6278;--line:#e4e9ef;--radius:12px}
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;
background:var(--bg);color:var(--text);line-height:1.55}
a{color:var(--blue)}
.header{background:linear-gradient(135deg,var(--blue) 0%,#163d70 100%);color:#fff;padding:1.1rem 1.5rem}
.header a{color:#fff;text-decoration:none;font-weight:700;font-size:1.25rem;letter-spacing:-.02em}
.header a span{color:var(--light)}
.wrap{max-width:760px;margin:0 auto;padding:1.5rem 1.25rem 3rem}
.crumb{font-size:.8rem;color:var(--text2);margin-bottom:1rem}
h1{font-size:1.65rem;line-height:1.25;margin-bottom:.35rem;letter-spacing:-.02em}
.meta{color:var(--text2);font-size:.9rem;margin-bottom:1.25rem}
.cta{display:inline-block;background:var(--blue);color:#fff;text-decoration:none;font-weight:600;
padding:.6rem 1.1rem;border-radius:var(--radius);font-size:.92rem;margin-bottom:1.5rem}
.card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);
padding:1.1rem 1.25rem;margin-bottom:1.5rem}
h2{font-size:1.05rem;margin-bottom:.7rem}
table{width:100%;border-collapse:collapse;font-size:.93rem}
th,td{text-align:left;padding:.45rem 0;border-bottom:1px solid var(--line)}
tr:last-child th,tr:last-child td{border-bottom:0}
th{font-weight:600;width:7.5rem}
td{color:var(--text2)}
.note{font-size:.86rem;color:var(--text2);margin-top:.8rem}
.pill-list{list-style:none;display:flex;flex-wrap:wrap;gap:.45rem;margin-top:.6rem}
.pill-list a{display:inline-block;background:var(--surface);border:1px solid var(--line);
border-radius:999px;padding:.28rem .8rem;font-size:.85rem;text-decoration:none}
.venue-list{list-style:none;display:grid;gap:.15rem}
.venue-row{display:grid;grid-template-columns:1fr;gap:.1rem;padding:.65rem 0;border-bottom:1px solid var(--line)}
.venue-row:last-child{border-bottom:0}
.venue-name{font-weight:600;text-decoration:none;font-size:.97rem}
.venue-loc{font-size:.82rem;color:var(--text2)}
.venue-week{font-size:.86rem;color:var(--text2);font-variant-numeric:tabular-nums}
.foot{font-size:.8rem;color:var(--text2);border-top:1px solid var(--line);padding-top:1rem;margin-top:2rem}
@media(max-width:520px){th{width:5.5rem;font-size:.88rem}td{font-size:.88rem}}
`.trim();

const chrome = (title, description, canonical, body, extraHead = '', noindex = false) => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${canonical}">
${noindex ? '<meta name="robots" content="noindex, follow">\n' : ''}
<link rel="icon" type="image/png" href="/assets/lionhour-favicon.png">
<meta property="og:type" content="website">
<meta property="og:url" content="${canonical}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:image" content="${ORIGIN}/assets/lionhour-social-hero-v7.png">
<meta name="twitter:card" content="summary_large_image">
<style>${STYLE}</style>
${extraHead}</head>
<body>
<header class="header"><a href="/">Lion<span>Hour</span></a></header>
<div class="wrap">
${body}
<p class="foot">Hours shown are the typical semester schedule published by Columbia. They shift during
breaks, holidays and exam periods — <a href="/">check the live tracker</a> before you go.
LionHour is a student project and is not affiliated with Columbia University.</p>
</div>
</body>
</html>
`;

/* ── 5. Venue pages ───────────────────────────────────────────────── */
mkdirSync(join(ROOT, 'hours'), { recursive: true });

let written = 0;
for (const v of pages) {
  const title = `${v.name} Hours — Columbia University | LionHour`;
  const summary = hasHours(v)
    ? `${v.name} (${v.loc}) opening hours for the current semester, updated live.`
    : `Live opening hours for ${v.name} at Columbia University (${v.loc}).`;
  const description = `${summary} See what's open on campus right now with LionHour.`.slice(0, 300);

  const rows = DAY_NAMES.map((d, i) =>
    `<tr><th>${d}</th><td>${esc(dayText(v.hours?.[i]))}</td></tr>`).join('\n');

  const siblings = (byCat[v.cat] || []).filter(s => s.slug !== v.slug).slice(0, 12);

  const jsonld = {
    '@context': 'https://schema.org',
    '@type': 'Place',
    name: v.name,
    url: v.url,
    address: {
      '@type': 'PostalAddress',
      streetAddress: v.loc,
      addressLocality: 'New York',
      addressRegion: 'NY',
      addressCountry: 'US',
    },
    containedInPlace: {
      '@type': 'CollegeOrUniversity',
      name: 'Columbia University',
      url: 'https://www.columbia.edu/',
    },
    ...(openingHoursSpec(v.hours).length
      ? { openingHoursSpecification: openingHoursSpec(v.hours) }
      : {}),
  };

  const breadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'LionHour', item: ORIGIN },
      { '@type': 'ListItem', position: 2, name: 'Campus hours', item: `${ORIGIN}/hours` },
      { '@type': 'ListItem', position: 3, name: CATEGORY[v.cat]?.plural ?? 'Buildings', item: `${ORIGIN}/hours/${CATEGORY[v.cat]?.slug}` },
      { '@type': 'ListItem', position: 4, name: `${v.name} hours`, item: v.url },
    ],
  };

  const cat = CATEGORY[v.cat];
  const body = `<p class="crumb"><a href="/">LionHour</a> › <a href="/hours">Campus hours</a> › <a href="/hours/${cat.slug}">${esc(cat.plural)}</a> › ${esc(v.name)}</p>
<h1>${esc(v.name)} hours</h1>
<p class="meta">${esc(v.catLabel)} · ${esc(v.loc)} · Columbia University, Morningside Heights</p>
<a class="cta" href="/">See if ${esc(v.name)} is open right now →</a>

<div class="card">
<h2>Weekly hours</h2>
<table>
${rows}
</table>
${v.note ? `<p class="note">${esc(v.note)}</p>` : ''}
${hasHours(v) ? '' : '<p class="note">This location publishes its schedule live rather than on a fixed weekly timetable. The <a href="/">LionHour tracker</a> shows the current hours.</p>'}
</div>

${siblings.length ? `<div class="card">
<h2><a href="/hours/${cat.slug}" style="text-decoration:none;color:inherit">Other ${esc(cat.plural.toLowerCase())} at Columbia →</a></h2>
<ul class="pill-list">
${siblings.map(s => `<li><a href="/hours/${s.slug}">${esc(s.name)}</a></li>`).join('\n')}
</ul>
</div>` : ''}`;

  const head = `<script type="application/ld+json">${JSON.stringify(jsonld)}</script>
<script type="application/ld+json">${JSON.stringify(breadcrumb)}</script>
`;

  writeFileSync(join(ROOT, 'hours', `${v.slug}.html`),
    chrome(title, description, v.url, body, head, NOINDEX.has(v.id)));
  written++;
}

/* ── 5b. Category pages ───────────────────────────────────────────── */
const catPages = [];
for (const [catId, meta] of Object.entries(CATEGORY)) {
  const list = byCat[catId] || [];
  if (!list.length) continue;
  const url = `${ORIGIN}/hours/${meta.slug}`;
  catPages.push({ ...meta, id: catId, url, count: list.length });

  const rows = list.map(p => `<li class="venue-row">
  <a class="venue-name" href="/hours/${p.slug}">${esc(p.name)}</a>
  <span class="venue-loc">${esc(p.loc)}</span>
  <span class="venue-week">${hasHours(p) ? esc(weekSummary(p.hours)) : 'Schedule loads live'}</span>
</li>`).join('\n');

  const itemList = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: meta.h1,
    url,
    numberOfItems: list.length,
    itemListElement: list.map((p, i) => ({
      '@type': 'ListItem', position: i + 1, name: p.name, url: p.url,
    })),
  };
  const breadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'LionHour', item: ORIGIN },
      { '@type': 'ListItem', position: 2, name: 'Campus hours', item: `${ORIGIN}/hours` },
      { '@type': 'ListItem', position: 3, name: meta.plural, item: url },
    ],
  };

  const others = Object.values(CATEGORY).filter(c => c.slug !== meta.slug && byCat[Object.keys(CATEGORY).find(k => CATEGORY[k] === c)]?.length);

  const body = `<p class="crumb"><a href="/">LionHour</a> › <a href="/hours">Campus hours</a> › ${esc(meta.plural)}</p>
<h1>${esc(meta.h1)}</h1>
<p class="meta">${list.length} locations · Columbia University, Morningside Heights</p>
<a class="cta" href="/?cat=${catId}">See which ${esc(meta.plural.toLowerCase())} are open right now →</a>
<p>${esc(meta.intro)}</p>

<div class="card">
<h2>Typical semester hours</h2>
<ul class="venue-list">
${rows}
</ul>
</div>

<div class="card">
<h2>Other places on campus</h2>
<ul class="pill-list">
${others.map(c => `<li><a href="/hours/${c.slug}">${esc(c.plural)}</a></li>`).join('\n')}
</ul>
</div>`;

  const head = `<script type="application/ld+json">${JSON.stringify(itemList)}</script>
<script type="application/ld+json">${JSON.stringify(breadcrumb)}</script>
`;
  writeFileSync(join(ROOT, 'hours', `${meta.slug}.html`), chrome(meta.title, meta.description, url, body, head));
}

/* ── 6. Hub page ──────────────────────────────────────────────────── */
const hubBody = `<p class="crumb"><a href="/">LionHour</a> › Campus hours</p>
<h1>Columbia University building hours</h1>
<p class="meta">Opening hours for ${pages.length} libraries, dining halls, cafes, gyms and student
services on Columbia's Morningside campus.</p>
<a class="cta" href="/">See what's open right now →</a>
${Object.entries(CATEGORY).filter(([c]) => byCat[c]?.length).map(([c, meta]) => `<div class="card">
<h2><a href="/hours/${meta.slug}" style="text-decoration:none;color:inherit">${esc(meta.plural)} →</a></h2>
<ul class="pill-list">
${byCat[c].map(p => `<li><a href="/hours/${p.slug}">${esc(p.name)}</a></li>`).join('\n')}
</ul>
</div>`).join('\n')}`;

writeFileSync(
  join(ROOT, 'hours', 'index.html'),
  chrome(
    'Columbia University Building Hours — Libraries, Dining, Gym | LionHour',
    `Opening hours for ${pages.length} Columbia University buildings: Butler Library, John Jay Dining, Dodge Gym, campus cafes and student services. Updated live.`,
    `${ORIGIN}/hours`,
    hubBody,
  ),
);

/* ── 7. sitemap.xml ───────────────────────────────────────────────── */
const today = new Date().toISOString().slice(0, 10);
const urls = [
  { loc: `${ORIGIN}/`, priority: '1.0', freq: 'hourly' },
  { loc: `${ORIGIN}/hours`, priority: '0.9', freq: 'daily' },
  ...catPages.map(c => ({ loc: c.url, priority: '0.8', freq: 'daily' })),
  ...pages.filter(p => !NOINDEX.has(p.id))
    .map(p => ({ loc: p.url, priority: '0.7', freq: 'weekly' })),
  { loc: `${ORIGIN}/privacy`, priority: '0.2', freq: 'yearly' },
];

writeFileSync(join(ROOT, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.freq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')}
</urlset>
`);

/* ── 8. robots.txt ────────────────────────────────────────────────── */
writeFileSync(join(ROOT, 'robots.txt'),
  `# lionhour.com
User-agent: *
Allow: /
Disallow: /api/
Disallow: /qr/

Sitemap: ${ORIGIN}/sitemap.xml
`);

console.log(`✓ ${written} venue pages + ${catPages.length} category pages + hub`);
console.log(`✓ sitemap.xml (${urls.length} URLs)`);
console.log(`✓ robots.txt`);
