#!/usr/bin/env node
/**
 * generate-seo.mjs — builds the crawlable surface of lionhour.com.
 *
 * Reads the VENUES catalog straight out of index.html (single source of
 * truth, so this can never drift from the app) and writes:
 *
 *   robots.txt              — crawl policy + sitemap pointer
 *   sitemap.xml             — every indexable URL
 *   hours/<slug>.html       — one static, indexable page per venue
 *   hours/index.html        — hub page linking every venue page
 *
 * The static pages carry the *typical semester* hours from the catalog and
 * link to the live tracker. They are regenerated by running:
 *
 *   npm run seo
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://lionhour.com';

/* Crisis / clinical services. The pages exist so the site is complete, but they
   are kept out of search: a student looking for these should land on Columbia's
   own page, not a student project. */
const NOINDEX = new Set(['svr', 'caps', 'medical', 'alice-health']);

/* ── 1. Pull the VENUES catalog out of index.html ─────────────────── */
const html = readFileSync(join(ROOT, 'index.html'), 'utf8');

const startMarker = 'const D = (mon, tue, wed, thu, fri, sat, sun)';
const start = html.indexOf(startMarker);
if (start === -1) throw new Error('Could not find the venue-data block in index.html');

const venuesDecl = html.indexOf('const VENUES', start);
if (venuesDecl === -1) throw new Error('Could not find `const VENUES` in index.html');

// The array ends at the first line that is exactly "];" after the declaration.
const endIdx = html.indexOf('\n];', venuesDecl);
if (endIdx === -1) throw new Error('Could not find the end of the VENUES array');

const src = html.slice(start, endIdx + 3);
const VENUES = new Function('window', `${src}\nreturn VENUES;`)({});

/* ── 2. Helpers ───────────────────────────────────────────────────── */
const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const SCHEMA_DAY = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

const CATEGORY = {
  library: { label: 'Library', plural: 'Libraries' },
  dining: { label: 'Dining hall', plural: 'Dining halls' },
  cafe: { label: 'Cafe', plural: 'Cafes' },
  fitness: { label: 'Fitness', plural: 'Gyms & fitness' },
  student: { label: 'Student services', plural: 'Student life & services' },
};

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
  .replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const slugify = name => name.toLowerCase()
  .replace(/['’]/g, '').replace(/&/g, 'and')
  .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/** "09:30" → "9:30 AM"; "24:00" → "midnight" */
function pretty(t) {
  const [hRaw, m] = t.split(':').map(Number);
  if (hRaw === 24 || (hRaw === 0 && m === 0)) return 'midnight';
  if (hRaw === 12 && m === 0) return 'noon';
  const h = hRaw % 12 === 0 ? 12 : hRaw % 12;
  const suffix = hRaw < 12 ? 'AM' : 'PM';
  return m === 0 ? `${h} ${suffix}` : `${h}:${String(m).padStart(2, '0')} ${suffix}`;
}

function dayText(ranges) {
  if (!ranges || !ranges.length) return 'Closed';
  if (ranges.length === 1 && ranges[0][0] === '00:00' && ranges[0][1] === '24:00') return 'Open 24 hours';
  return ranges.map(([o, c]) => `${pretty(o)} – ${pretty(c)}`).join(', ');
}

/** schema.org wants 24h HH:MM; 24:00 is not valid, use 23:59. */
const schemaTime = t => (t === '24:00' ? '23:59' : t);

function openingHoursSpec(hours) {
  const spec = [];
  for (let d = 0; d < 7; d++) {
    const ranges = hours?.[d];
    if (!ranges || !ranges.length) continue;
    for (const [o, c] of ranges) {
      spec.push({
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: `https://schema.org/${SCHEMA_DAY[d]}`,
        opens: schemaTime(o),
        closes: schemaTime(c),
      });
    }
  }
  return spec;
}

const hasHours = v => Array.from({ length: 7 }, (_, d) => v.hours?.[d]).some(r => r && r.length);

/* ── 3. Build the venue list ──────────────────────────────────────── */
const pages = VENUES.map(v => ({
  ...v,
  slug: slugify(v.name),
  url: `${ORIGIN}/hours/${slugify(v.name)}`,
  catLabel: CATEGORY[v.cat]?.label ?? 'Building',
}));

const byCat = {};
for (const p of pages) (byCat[p.cat] ||= []).push(p);

/* ── 4. Shared chrome ─────────────────────────────────────────────── */
const STYLE = `
:root{--blue:#1D4F91;--light:#75AADB;--bg:#F0F4F8;--surface:#fff;--text:#1a1a2e;
--text2:#5a6278;--line:#e4e9ef;--radius:12px}
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;
background:var(--bg);color:var(--text);line-height:1.55}
a{color:var(--blue)}
.header{background:linear-gradient(135deg,var(--blue) 0%,#163d70 100%);color:#fff;padding:1.1rem 1.5rem}
.header a{color:#fff;text-decoration:none;font-weight:700;font-size:1.25rem;letter-spacing:-.02em}
.header a span{color:var(--light)}
.wrap{max-width:760px;margin:0 auto;padding:1.5rem 1.25rem 3rem}
.crumb{font-size:.8rem;color:var(--text2);margin-bottom:1rem}
h1{font-size:1.65rem;line-height:1.25;margin-bottom:.35rem;letter-spacing:-.02em}
.meta{color:var(--text2);font-size:.9rem;margin-bottom:1.25rem}
.cta{display:inline-block;background:var(--blue);color:#fff;text-decoration:none;font-weight:600;
padding:.6rem 1.1rem;border-radius:var(--radius);font-size:.92rem;margin-bottom:1.5rem}
.card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);
padding:1.1rem 1.25rem;margin-bottom:1.5rem}
h2{font-size:1.05rem;margin-bottom:.7rem}
table{width:100%;border-collapse:collapse;font-size:.93rem}
th,td{text-align:left;padding:.45rem 0;border-bottom:1px solid var(--line)}
tr:last-child th,tr:last-child td{border-bottom:0}
th{font-weight:600;width:7.5rem}
td{color:var(--text2)}
.note{font-size:.86rem;color:var(--text2);margin-top:.8rem}
.pill-list{list-style:none;display:flex;flex-wrap:wrap;gap:.45rem;margin-top:.6rem}
.pill-list a{display:inline-block;background:var(--surface);border:1px solid var(--line);
border-radius:999px;padding:.28rem .8rem;font-size:.85rem;text-decoration:none}
.foot{font-size:.8rem;color:var(--text2);border-top:1px solid var(--line);padding-top:1rem;margin-top:2rem}
@media(max-width:520px){th{width:5.5rem;font-size:.88rem}td{font-size:.88rem}}
`.trim();

const chrome = (title, description, canonical, body, extraHead = '', noindex = false) => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${canonical}">
${noindex ? '<meta name="robots" content="noindex, follow">\n' : ''}
<link rel="icon" type="image/png" href="/assets/lionhour-favicon.png">
<meta property="og:type" content="website">
<meta property="og:url" content="${canonical}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:image" content="${ORIGIN}/assets/lionhour-social-hero-v7.png">
<meta name="twitter:card" content="summary_large_image">
<style>${STYLE}</style>
${extraHead}</head>
<body>
<header class="header"><a href="/">Lion<span>Hour</span></a></header>
<div class="wrap">
${body}
<p class="foot">Hours shown are the typical semester schedule published by Columbia. They shift during
breaks, holidays and exam periods — <a href="/">check the live tracker</a> before you go.
LionHour is a student project and is not affiliated with Columbia University.</p>
</div>
</body>
</html>
`;

/* ── 5. Venue pages ───────────────────────────────────────────────── */
mkdirSync(join(ROOT, 'hours'), { recursive: true });

let written = 0;
for (const v of pages) {
  const title = `${v.name} Hours — Columbia University | LionHour`;
  const summary = hasHours(v)
    ? `${v.name} (${v.loc}) opening hours for the current semester, updated live.`
    : `Live opening hours for ${v.name} at Columbia University (${v.loc}).`;
  const description = `${summary} See what's open on campus right now with LionHour.`.slice(0, 300);

  const rows = DAY_NAMES.map((d, i) =>
    `<tr><th>${d}</th><td>${esc(dayText(v.hours?.[i]))}</td></tr>`).join('\n');

  const siblings = (byCat[v.cat] || []).filter(s => s.slug !== v.slug).slice(0, 12);

  const jsonld = {
    '@context': 'https://schema.org',
    '@type': 'Place',
    name: v.name,
    url: v.url,
    address: {
      '@type': 'PostalAddress',
      streetAddress: v.loc,
      addressLocality: 'New York',
      addressRegion: 'NY',
      addressCountry: 'US',
    },
    containedInPlace: {
      '@type': 'CollegeOrUniversity',
      name: 'Columbia University',
      url: 'https://www.columbia.edu/',
    },
    ...(openingHoursSpec(v.hours).length
      ? { openingHoursSpecification: openingHoursSpec(v.hours) }
      : {}),
  };

  const breadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'LionHour', item: ORIGIN },
      { '@type': 'ListItem', position: 2, name: 'Campus hours', item: `${ORIGIN}/hours` },
      { '@type': 'ListItem', position: 3, name: `${v.name} hours`, item: v.url },
    ],
  };

  const body = `<p class="crumb"><a href="/">LionHour</a> › <a href="/hours">Campus hours</a> › ${esc(v.name)}</p>
<h1>${esc(v.name)} hours</h1>
<p class="meta">${esc(v.catLabel)} · ${esc(v.loc)} · Columbia University, Morningside Heights</p>
<a class="cta" href="/">See if ${esc(v.name)} is open right now →</a>

<div class="card">
<h2>Weekly hours</h2>
<table>
${rows}
</table>
${v.note ? `<p class="note">${esc(v.note)}</p>` : ''}
${hasHours(v) ? '' : '<p class="note">This location publishes its schedule live rather than on a fixed weekly timetable. The <a href="/">LionHour tracker</a> shows the current hours.</p>'}
</div>

${siblings.length ? `<div class="card">
<h2>Other ${esc((CATEGORY[v.cat]?.plural ?? 'places').toLowerCase())} at Columbia</h2>
<ul class="pill-list">
${siblings.map(s => `<li><a href="/hours/${s.slug}">${esc(s.name)}</a></li>`).join('\n')}
</ul>
</div>` : ''}`;

  const head = `<script type="application/ld+json">${JSON.stringify(jsonld)}</script>
<script type="application/ld+json">${JSON.stringify(breadcrumb)}</script>
`;

  writeFileSync(join(ROOT, 'hours', `${v.slug}.html`),
    chrome(title, description, v.url, body, head, NOINDEX.has(v.id)));
  written++;
}

/* ── 6. Hub page ──────────────────────────────────────────────────── */
const hubBody = `<p class="crumb"><a href="/">LionHour</a> › Campus hours</p>
<h1>Columbia University building hours</h1>
<p class="meta">Opening hours for ${pages.length} libraries, dining halls, cafes, gyms and student
services on Columbia's Morningside campus.</p>
<a class="cta" href="/">See what's open right now →</a>
${Object.entries(CATEGORY).filter(([c]) => byCat[c]?.length).map(([c, meta]) => `<div class="card">
<h2>${esc(meta.plural)}</h2>
<ul class="pill-list">
${byCat[c].map(p => `<li><a href="/hours/${p.slug}">${esc(p.name)}</a></li>`).join('\n')}
</ul>
</div>`).join('\n')}`;

writeFileSync(
  join(ROOT, 'hours', 'index.html'),
  chrome(
    'Columbia University Building Hours — Libraries, Dining, Gym | LionHour',
    `Opening hours for ${pages.length} Columbia University buildings: Butler Library, John Jay Dining, Dodge Gym, campus cafes and student services. Updated live.`,
    `${ORIGIN}/hours`,
    hubBody,
  ),
);

/* ── 7. sitemap.xml ───────────────────────────────────────────────── */
const today = new Date().toISOString().slice(0, 10);
const urls = [
  { loc: `${ORIGIN}/`, priority: '1.0', freq: 'hourly' },
  { loc: `${ORIGIN}/hours`, priority: '0.9', freq: 'daily' },
  ...pages.filter(p => !NOINDEX.has(p.id))
    .map(p => ({ loc: p.url, priority: '0.7', freq: 'weekly' })),
  { loc: `${ORIGIN}/privacy`, priority: '0.2', freq: 'yearly' },
];

writeFileSync(join(ROOT, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.freq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')}
</urlset>
`);

/* ── 8. robots.txt ────────────────────────────────────────────────── */
writeFileSync(join(ROOT, 'robots.txt'),
  `# lionhour.com
User-agent: *
Allow: /
Disallow: /api/
Disallow: /qr/

Sitemap: ${ORIGIN}/sitemap.xml
`);

console.log(`✓ ${written} venue pages + hub`);
console.log(`✓ sitemap.xml (${urls.length} URLs)`);
console.log(`✓ robots.txt`);
